site_name: before
site_description: A cool quarkus chatbot app
repo_url: https://gitlab-gitlab.apps.cluster-k4c8v.k4c8v.sandbox3234.opentlc.com/development/before
edit_uri: edit/master/docs

plugins:
  - techdocs-core

# Note for content editors, edit only the section below
nav:
  - Onboard a developer to OpenShift: onboard-openshift.md
  - Application Migration:
      - Migration Process Overview: application-migration/migration-process-overview.md
      - Migration Process Steps: application-migration/migration-process-steps.md
      - Learning Path for Developers: application-migration/learning-path-for-developers.md
